In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array(['asd', 'sdf'])

array(['asd', 'sdf'], dtype='<U3')

In [4]:
np.array([1,2.1,3])

array([1. , 2.1, 3. ])

In [5]:
np.array([1,'as'])

array(['1', 'as'], dtype='<U21')

In [6]:
[1,2,3]

[1, 2, 3]

In [8]:
a = np.array([1,2,3])
a.shape

(3,)

In [9]:
b = np.array([[1,2,3]])
b.shape

(1, 3)

In [10]:
b.shape[0]

1

In [11]:
[1,2]*2

[1, 2, 1, 2]

In [12]:
list1 = [1,2,3]
list2 = [2,3,4]
list(map(lambda x,y:x*y, list1, list2))

[2, 6, 12]

In [13]:
a1 = np.array(list1)
a2 = np.array(list2)
a1*a2

array([ 2,  6, 12])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.random((3,4))

array([[0.10743321, 0.50426112, 0.21305093, 0.53687122],
       [0.60188924, 0.4597507 , 0.03080415, 0.13117368],
       [0.10872405, 0.90677605, 0.83212355, 0.83520569]])

In [17]:
np.zeros((2,3), dtype=np.uint8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [18]:
np.ones([2,3], dtype=np.uint8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [20]:
np.random.random([3,5])

array([[0.88114375, 0.48704876, 0.12504659, 0.69355933, 0.58997726],
       [0.58299477, 0.5094879 , 0.25732073, 0.20690821, 0.27913008],
       [0.81517625, 0.13773958, 0.75303415, 0.01190054, 0.92007629]])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [22]:
np.linspace(2,5,100)

array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
       2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
       2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
       2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
       2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
       2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
       2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
       3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
       3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
       3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
       3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
       3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
       3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
       3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
       4.12121212, 4.15151515, 4.18181818, 4.21212121, 4.24242

In [23]:
a = np.random.random([4,5])

In [24]:
a.sum(axis=0)

array([1.64162735, 2.6367004 , 2.57569895, 3.02805912, 1.37740396])

In [25]:
a.sum(axis=1)

array([2.25611344, 2.97043031, 3.40857765, 2.62436838])

In [26]:
a.shape

(4, 5)

In [29]:
a.ndim

2

In [30]:
a.itemsize

8

In [31]:
a.dtype

dtype('float64')

In [34]:
a = np.random.randint(0, 20, (3,4,5))

In [37]:
a

array([[[ 8,  9, 14,  7, 12],
        [19,  6, 12,  8, 15],
        [17,  2,  2, 11, 12],
        [19,  4, 18,  6, 17]],

       [[ 8, 19, 15, 11,  3],
        [ 1,  3,  6, 18,  3],
        [ 7, 18, 11, 16,  6],
        [ 0,  1, 11,  6,  9]],

       [[ 3, 19,  5, 18, 13],
        [15,  9, 14, 18, 12],
        [12, 16,  7, 13,  3],
        [16,  9, 13, 19, 14]]])

In [38]:
a.sum(axis=0).shape

(4, 5)

In [39]:
a.sum(axis=1).shape

(3, 5)

In [40]:
a.sum(axis=2).shape

(3, 4)

In [42]:
a[1, 1,: ]

array([ 1,  3,  6, 18,  3])

In [44]:
a[0, :, 0]

array([ 8, 19, 17, 19])

In [45]:
for row in a:
    print(row)
    break

[[ 8  9 14  7 12]
 [19  6 12  8 15]
 [17  2  2 11 12]
 [19  4 18  6 17]]


In [47]:
a[0,:,:].shape

(4, 5)

In [49]:
import time
list1 = [x for x in range(100000)]
list2 = [x*2 for x in range(100000)]
t0 = time.time()
out1 = list(map(lambda x,y: x*y, list1, list2))
t1 = time.time()
d1 = t1-t0
print(d1)
l1 = np.array(list1)
l2 = np.array(list2)
t0 = time.time()
out2 = l1*l2
t1 = time.time()
d2 = t1-t0
print(d2)
print(d1/d2)

0.035952091217041016
0.0008783340454101562
40.93213897937025


In [50]:
a1 = np.arange(0,12)

In [51]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
a1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a1 = np.arange(0,24)

In [54]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
a1.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
a1.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [57]:
a1 = [[1,2],[3,4]]

b1 = [[5,6],[7,8]]

c1 = [9,1,2,5]

In [59]:
h = np.hstack((a1,b1))
np.vstack((h, c1))

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [9, 1, 2, 5]])

In [60]:
a1 = np.array([[1,2],[3,4]])

b1 = np.array([[5,6],[7,8]])

c1 = np.array([9,1,2,5])

In [61]:
h = np.hstack(a1,b1)
np.vstack(h, c1)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [83]:
import time
import random
a = list(range(1,100000))
a1 = np.array(a)
t0 = time.time()
b = [x/(x+1) for x in a]
t1 = time.time()
q = t1-t0
print(q)
t0 = time.time()
b1 = a1/(a1+1)
t1 = time.time()
q1 = t1-t0
print(q1)
t0 = time.time()
b2 = np.vectorize(lambda x: x/(x+1))
b2(a)
t1 = time.time()
q2 = t1-t0
print(q2)

0.017863750457763672
0.002743959426879883
0.0615692138671875


In [84]:
q2/q1

22.438091928056302

In [85]:
q/q1

6.510209401338083

In [86]:
q2/q

3.4466006459706913

In [87]:
def func(x)  
    return x/(x+1)

In [88]:
result = np.vectorize(func)

In [89]:
a = list(range(1,10))
result(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       ])

In [90]:
import pandas as pd

In [94]:
q = pd.Series([1,2,3])

In [93]:
pd.Series([1.2, 3.4])

0    1.2
1    3.4
dtype: float64

In [100]:
q[0:2]

0    1
1    2
dtype: int64

In [101]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

In [102]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [107]:
pd.date_range(start = '11/09/2020', end = '12/11/2020')

DatetimeIndex(['2020-11-09', '2020-11-10', '2020-11-11', '2020-11-12',
               '2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16',
               '2020-11-17', '2020-11-18', '2020-11-19', '2020-11-20',
               '2020-11-21', '2020-11-22', '2020-11-23', '2020-11-24',
               '2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
               '2020-11-29', '2020-11-30', '2020-12-01', '2020-12-02',
               '2020-12-03', '2020-12-04', '2020-12-05', '2020-12-06',
               '2020-12-07', '2020-12-08', '2020-12-09', '2020-12-10',
               '2020-12-11'],
              dtype='datetime64[ns]', freq='D')

In [112]:
a = np.random.random([4,5])

In [113]:
a

array([[0.24818008, 0.40453938, 0.28680416, 0.88876927, 0.74896778],
       [0.75199621, 0.12338905, 0.54094141, 0.65624881, 0.68476552],
       [0.11633063, 0.50582668, 0.70951394, 0.82700945, 0.73709576],
       [0.91809952, 0.30870303, 0.44339648, 0.5265778 , 0.58498881]])

In [119]:
a[0]

array([0.24818008, 0.40453938, 0.28680416, 0.88876927, 0.74896778])

In [127]:
f = pd.Series(np.arange(10))

In [128]:
f

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [130]:
f[[0,1,2,9]]

0    0
1    1
2    2
9    9
dtype: int64

In [131]:
f.apply(lambda x: x**2)

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [132]:
f[:]**2

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [134]:
pd.Series([1,2,3], index=['a','b','c'])

a    1
b    2
c    3
dtype: int64

In [136]:
a = {'name': ['kk','ll','dd'], 'age':[12, 34, 56]}
v = pd.DataFrame(a)

In [139]:
v.tail()

name  age
0   kk   12
1   ll   34
2   dd   56

In [2]:
import pandas as pd
mf = pd.read_csv("global_sales_data/market_fact.csv")

In [1]:
import os
os.getcwd()

'/home/jarvis/jarvis/upgrad/masters/prep/pandas'

In [3]:
os.listdir('.')

['dummy.ipynb',
 '.ipynb_checkpoints',
 '6_Grouping_and_Summarising.ipynb',
 'global_sales_data',
 '7_Lambda_Functions_Pivot_Tables.ipynb',
 '5__Merging_Concatenating.ipynb',
 '2_Indexing_and_Selecting_Data.ipynb',
 '3_Position_and_Label_Based_Indexing.ipynb',
 '1__Pandas_Basics.ipynb',
 '4_Slicing_Dicing.ipynb']

In [4]:
mf.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [5]:
mf.tail()

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
8394              28  374.63           7.69                 0.59  
8395              20  -74.03           6.92                 0.37  
8396              39  -70.85           5.35                 0.40  
8397              23  565.34          30.00                 0.62  
8398              47  131.39           4.86                 0.38

In [6]:
mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Ord_id               8399 non-null   object 
 1   Prod_id              8399 non-null   object 
 2   Ship_id              8399 non-null   object 
 3   Cust_id              8399 non-null   object 
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64  
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB


In [7]:
mf.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin  
count          8336.000000  
mean              0.512513  
std               0.135589  
min               0.350000  
25%               0.380000  
50%               0.520000  
75%               0.590000  
max               0.850000

In [8]:
mf.columns

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

In [9]:
mf.values

array([['Ord_5446', 'Prod_16', 'SHP_7609', ..., -30.51, 3.6, 0.56],
       ['Ord_5406', 'Prod_13', 'SHP_7549', ..., 4.56, 0.93, 0.54],
       ['Ord_5446', 'Prod_4', 'SHP_7610', ..., 1148.9, 2.5, 0.59],
       ...,
       ['Ord_5388', 'Prod_6', 'SHP_7524', ..., -70.85, 5.35, 0.4],
       ['Ord_5348', 'Prod_15', 'SHP_7469', ..., 565.34, 30.0, 0.62],
       ['Ord_5459', 'Prod_6', 'SHP_7628', ..., 131.39, 4.86, 0.38]],
      dtype=object)

In [10]:
mf.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [12]:
mf[2:3]

Ord_id Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
2  Ord_5446  Prod_4  SHP_7610  Cust_1818  4701.69       0.0              26   

   Profit  Shipping_Cost  Product_Base_Margin  
2  1148.9            2.5                 0.59

In [15]:
mf[:1][['Ord_id', 'Prod_id']]

Ord_id  Prod_id
0  Ord_5446  Prod_16

In [14]:
mf.iloc[:2,:]

Ord_id  Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818  136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818   42.27      0.01              13   

   Profit  Shipping_Cost  Product_Base_Margin  
0  -30.51           3.60                 0.56  
1    4.56           0.93                 0.54

In [22]:
type(mf.iloc[:,:1])

pandas.core.frame.DataFrame

In [27]:
mf.iloc[[0,1,2],[0,1]]

Ord_id  Prod_id
0  Ord_5446  Prod_16
1  Ord_5406  Prod_13
2  Ord_5446   Prod_4

In [43]:
mf
type(pd.Series([True,False]))

pandas.core.series.Series

In [38]:
type(mf.Sales>3000)

pandas.core.series.Series

In [47]:
mf.loc[(mf.Sales<3000) & (mf.Sales>2000)]

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
81    Ord_5205   Prod_4  SHP_7274  Cust_1749  2546.5235      0.09   
98    Ord_5481  Prod_15  SHP_7659  Cust_1820  2700.7800      0.06   
109    Ord_139  Prod_17   SHP_186    Cust_45  2671.2100      0.06   
110    Ord_239   Prod_4   SHP_332    Cust_45  2157.3085      0.00   
...        ...      ...       ...        ...        ...       ...   
8351  Ord_3584  Prod_15  SHP_4961  Cust_1266  2502.6700      0.10   
8354  Ord_3592   Prod_4  SHP_4973  Cust_1266  2614.3705      0.07   
8360  Ord_3639  Prod_10  SHP_5038  Cust_1266  2173.2600      0.00   
8381  Ord_2696   Prod_4  SHP_3691  Cust_1006  2836.0505      0.01   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
3                 43  729.34          14.30                 0.37  
81                26  210.00           7.69                 0.59  
98                29 -793.36          58.20                 0.58  
109               14  636.18          15.59                 0.36  
110               38  519.25           5.31                 0.57  
...              ...     ...            ...                  ...  
8351               9 -198.80          64.73                 0.56  
8354              25  384.01           7.69                 0.58  
8360              35 -465.66          36.61                 0.61  
8381              25  561.13           8.99                 0.59  
8394              28  374.63           7.69                 0.59  

[513 rows x 10 columns]

In [48]:
import os
os.getcwd()

'/home/jarvis/jarvis/upgrad/masters/prep/pandas'

In [49]:
os.listdir()

['dummy.ipynb',
 '.ipynb_checkpoints',
 '6_Grouping_and_Summarising.ipynb',
 'global_sales_data',
 '7_Lambda_Functions_Pivot_Tables.ipynb',
 '5__Merging_Concatenating.ipynb',
 '2_Indexing_and_Selecting_Data.ipynb',
 '3_Position_and_Label_Based_Indexing.ipynb',
 '1__Pandas_Basics.ipynb',
 '4_Slicing_Dicing.ipynb']

In [50]:
market_df = pd.read_csv("./global_sales_data/market_fact.csv")
customer_df = pd.read_csv("./global_sales_data/cust_dimen.csv")
product_df = pd.read_csv("./global_sales_data/prod_dimen.csv")
shipping_df = pd.read_csv("./global_sales_data/shipping_dimen.csv")
orders_df = pd.read_csv("./global_sales_data/orders_dimen.csv")

In [51]:
market_df.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [52]:
customer_df.head()

Customer_Name Province   Region Customer_Segment Cust_id
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_1
1        BARRY FRENCH  NUNAVUT  NUNAVUT         CONSUMER  Cust_2
2       CLAY ROZENDAL  NUNAVUT  NUNAVUT        CORPORATE  Cust_3
3      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER  Cust_4
4        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE  Cust_5

In [53]:
product_df.head()

Product_Category            Product_Sub_Category Prod_id
0  OFFICE SUPPLIES          STORAGE & ORGANIZATION  Prod_1
1  OFFICE SUPPLIES                      APPLIANCES  Prod_2
2  OFFICE SUPPLIES  BINDERS AND BINDER ACCESSORIES  Prod_3
3       TECHNOLOGY    TELEPHONES AND COMMUNICATION  Prod_4
4        FURNITURE              OFFICE FURNISHINGS  Prod_5

In [54]:
df_1 = pd.merge(market_df, customer_df, how='inner', on='Cust_id')

In [56]:
df_2 = pd.merge(df_1, product_df, how='inner', on='Prod_id')

In [60]:
df_3 = pd.merge(df_2, shipping_df, how='inner', on='Ship_id')

In [63]:
df_4 = pd.merge(df_3, orders_df, how='inner', on='Ord_id')

In [64]:
df_4.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
2  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   
3  Ord_2978  Prod_16  SHP_4112  Cust_1088   305.05      0.04              27   
4  Ord_5484  Prod_16  SHP_7663  Cust_1820   322.82      0.05              35   

    Profit  Shipping_Cost  Product_Base_Margin  ...   Region Customer_Segment  \
0   -30.51           3.60                 0.56  ...     WEST        CORPORATE   
1  1148.90           2.50                 0.59  ...     WEST        CORPORATE   
2   -47.64           6.15                 0.37  ...     WEST        CORPORATE   
3    23.12           3.37                 0.57  ...  ONTARIO      HOME OFFICE   
4   -17.58           3.98                 0.56  ...     WEST         CONSUMER   

  Product_Category           Product_Sub_Category Order_ID_x    Ship_Mode  \
0  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      36262  REGULAR AIR   
1       TECHNOLOGY   TELEPHONES AND COMMUNICATION      36262  EXPRESS AIR   
2  OFFICE SUPPLIES                          PAPER      36262  EXPRESS AIR   
3  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      37863  REGULAR AIR   
4  OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS      53026  REGULAR AIR   

    Ship_Date Order_ID_y  Order_Date  Order_Priority  
0  28-07-2010      36262  27-07-2010   NOT SPECIFIED  
1  27-07-2010      36262  27-07-2010   NOT SPECIFIED  
2  28-07-2010      36262  27-07-2010   NOT SPECIFIED  
3  26-02-2011      37863  24-02-2011            HIGH  
4  03-03-2012      53026  26-02-2012             LOW  

[5 rows x 22 columns]

In [65]:
df_4_grp = df_4.groupby('Customer_Segment')

In [68]:
df_4_grp['Order_Quantity'].sum()

Customer_Segment
CONSUMER          41760
CORPORATE         78517
HOME OFFICE       52807
SMALL BUSINESS    41693
Name: Order_Quantity, dtype: int64

In [69]:
pd.DataFrame(df_4_grp['Order_Quantity'].sum().sort_values(ascending=False))

Order_Quantity
Customer_Segment                
CORPORATE                  78517
HOME OFFICE                52807
CONSUMER                   41760
SMALL BUSINESS             41693